mobs-blacklist:
  - 'COW'
  - 'CHICKEN'

cooldown:
  vip:
    ordem: 1
    cooldown: 1
    permissao: ''
  default:
    ordem: 2
    cooldown: 2
    permissao: ''

menu:
  linhas: 3 # Define o número de linhas do menu
  titulo: 'AutoClicker' # Define o título do menu
  alternar:
    slot: 13 # Define o slot onde o item será colocado
    material: '325' # MATERIAL:DATA, ID:DATA, ou TEXTURA para cabeças personalizadas
    nome: '&bAutoClicker' # {status] pode ser usado tanto no nome como na lore
    lore:
      - '&7O autoclicker permite você'
      - '&7matar mobs sem clicar em'
      - '&7um único botão.'
      - ''
      - '&f Delay: &7{cooldown} segundos'
      - ''
      - '&fClique para {status}&f.'

  #item1:  É possivel criar itens de decoração
    #slot: 14
    #material: 'SIGN'
    #nome: '&6Informação'
    #lore:
    #  - '&fDelay: &7{cooldown}'
    #  - ''
    #  - ''

mensagens: #deixe vazio para não usar
  ativado: '&aAutoClick ativado com sucesso'
  desativado: '&cAutoClick desativado com sucesso'
  ja-ativado: '&aO Autoclick já se encontra ativado.'
  ja-desativado: '&cO Autoclick já se encontra desativado.'
  comando-invalido: '&cUso inválido. Use /ac [on|off]'


status:
  ativar: '&aativar'
  desativar: '&cdesativar'

